//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidatorExample.ValidationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationResult", Namespace="http://validator.dmbasis.ru/phone/")]
    [System.SerializableAttribute()]
    public partial class ValidationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RawPhoneCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RawPhoneNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProviderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeZoneField;
        
        private int StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RecordId {
            get {
                return this.RecordIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordIdField, value) != true)) {
                    this.RecordIdField = value;
                    this.RaisePropertyChanged("RecordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RawPhoneCode {
            get {
                return this.RawPhoneCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RawPhoneCodeField, value) != true)) {
                    this.RawPhoneCodeField = value;
                    this.RaisePropertyChanged("RawPhoneCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RawPhoneNum {
            get {
                return this.RawPhoneNumField;
            }
            set {
                if ((object.ReferenceEquals(this.RawPhoneNumField, value) != true)) {
                    this.RawPhoneNumField = value;
                    this.RaisePropertyChanged("RawPhoneNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PhoneCode {
            get {
                return this.PhoneCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneCodeField, value) != true)) {
                    this.PhoneCodeField = value;
                    this.RaisePropertyChanged("PhoneCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PhoneNum {
            get {
                return this.PhoneNumField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumField, value) != true)) {
                    this.PhoneNumField = value;
                    this.RaisePropertyChanged("PhoneNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string PhoneType {
            get {
                return this.PhoneTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneTypeField, value) != true)) {
                    this.PhoneTypeField = value;
                    this.RaisePropertyChanged("PhoneType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Provider {
            get {
                return this.ProviderField;
            }
            set {
                if ((object.ReferenceEquals(this.ProviderField, value) != true)) {
                    this.ProviderField = value;
                    this.RaisePropertyChanged("Provider");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string TimeZone {
            get {
                return this.TimeZoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeZoneField, value) != true)) {
                    this.TimeZoneField = value;
                    this.RaisePropertyChanged("TimeZone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationRequest", Namespace="http://validator.dmbasis.ru/phone/")]
    [System.SerializableAttribute()]
    public partial class ValidationRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RecordId {
            get {
                return this.RecordIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RecordIdField, value) != true)) {
                    this.RecordIdField = value;
                    this.RaisePropertyChanged("RecordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PhoneCode {
            get {
                return this.PhoneCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneCodeField, value) != true)) {
                    this.PhoneCodeField = value;
                    this.RaisePropertyChanged("PhoneCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PhoneNum {
            get {
                return this.PhoneNumField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumField, value) != true)) {
                    this.PhoneNumField = value;
                    this.RaisePropertyChanged("PhoneNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobStatusResult", Namespace="http://validator.dmbasis.ru/phone/")]
    [System.SerializableAttribute()]
    public partial class JobStatusResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        private int CountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Count {
            get {
                return this.CountField;
            }
            set {
                if ((this.CountField.Equals(value) != true)) {
                    this.CountField = value;
                    this.RaisePropertyChanged("Count");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://validator.dmbasis.ru/phone/", ConfigurationName="ValidationService.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name phoneCode from namespace http://validator.dmbasis.ru/phone/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://validator.dmbasis.ru/phone/Validate", ReplyAction="*")]
        ValidatorExample.ValidationService.ValidateResponse Validate(ValidatorExample.ValidationService.ValidateRequest request);
        
        // CODEGEN: Generating message contract since element name batch from namespace http://validator.dmbasis.ru/phone/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://validator.dmbasis.ru/phone/ValidateBatch", ReplyAction="*")]
        ValidatorExample.ValidationService.ValidateBatchResponse ValidateBatch(ValidatorExample.ValidationService.ValidateBatchRequest request);
        
        // CODEGEN: Generating message contract since element name GetJobStatusResult from namespace http://validator.dmbasis.ru/phone/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://validator.dmbasis.ru/phone/GetJobStatus", ReplyAction="*")]
        ValidatorExample.ValidationService.GetJobStatusResponse GetJobStatus(ValidatorExample.ValidationService.GetJobStatusRequest request);
        
        // CODEGEN: Generating message contract since element name GetValidationResultResult from namespace http://validator.dmbasis.ru/phone/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://validator.dmbasis.ru/phone/GetValidationResult", ReplyAction="*")]
        ValidatorExample.ValidationService.GetValidationResultResponse GetValidationResult(ValidatorExample.ValidationService.GetValidationResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://validator.dmbasis.ru/phone/StartJob", ReplyAction="*")]
        int StartJob(System.Guid jobId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Validate", Namespace="http://validator.dmbasis.ru/phone/", Order=0)]
        public ValidatorExample.ValidationService.ValidateRequestBody Body;
        
        public ValidateRequest() {
        }
        
        public ValidateRequest(ValidatorExample.ValidationService.ValidateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://validator.dmbasis.ru/phone/")]
    public partial class ValidateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string phoneCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string phoneNum;
        
        public ValidateRequestBody() {
        }
        
        public ValidateRequestBody(string phoneCode, string phoneNum) {
            this.phoneCode = phoneCode;
            this.phoneNum = phoneNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateResponse", Namespace="http://validator.dmbasis.ru/phone/", Order=0)]
        public ValidatorExample.ValidationService.ValidateResponseBody Body;
        
        public ValidateResponse() {
        }
        
        public ValidateResponse(ValidatorExample.ValidationService.ValidateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://validator.dmbasis.ru/phone/")]
    public partial class ValidateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ValidatorExample.ValidationService.ValidationResult[] ValidateResult;
        
        public ValidateResponseBody() {
        }
        
        public ValidateResponseBody(ValidatorExample.ValidationService.ValidationResult[] ValidateResult) {
            this.ValidateResult = ValidateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateBatchRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateBatch", Namespace="http://validator.dmbasis.ru/phone/", Order=0)]
        public ValidatorExample.ValidationService.ValidateBatchRequestBody Body;
        
        public ValidateBatchRequest() {
        }
        
        public ValidateBatchRequest(ValidatorExample.ValidationService.ValidateBatchRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://validator.dmbasis.ru/phone/")]
    public partial class ValidateBatchRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ValidatorExample.ValidationService.ValidationRequest[] batch;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool withManualChecking;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userName;
        
        public ValidateBatchRequestBody() {
        }
        
        public ValidateBatchRequestBody(ValidatorExample.ValidationService.ValidationRequest[] batch, bool withManualChecking, string userName) {
            this.batch = batch;
            this.withManualChecking = withManualChecking;
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateBatchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateBatchResponse", Namespace="http://validator.dmbasis.ru/phone/", Order=0)]
        public ValidatorExample.ValidationService.ValidateBatchResponseBody Body;
        
        public ValidateBatchResponse() {
        }
        
        public ValidateBatchResponse(ValidatorExample.ValidationService.ValidateBatchResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://validator.dmbasis.ru/phone/")]
    public partial class ValidateBatchResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid ValidateBatchResult;
        
        public ValidateBatchResponseBody() {
        }
        
        public ValidateBatchResponseBody(System.Guid ValidateBatchResult) {
            this.ValidateBatchResult = ValidateBatchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetJobStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetJobStatus", Namespace="http://validator.dmbasis.ru/phone/", Order=0)]
        public ValidatorExample.ValidationService.GetJobStatusRequestBody Body;
        
        public GetJobStatusRequest() {
        }
        
        public GetJobStatusRequest(ValidatorExample.ValidationService.GetJobStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://validator.dmbasis.ru/phone/")]
    public partial class GetJobStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid jobId;
        
        public GetJobStatusRequestBody() {
        }
        
        public GetJobStatusRequestBody(System.Guid jobId) {
            this.jobId = jobId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetJobStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetJobStatusResponse", Namespace="http://validator.dmbasis.ru/phone/", Order=0)]
        public ValidatorExample.ValidationService.GetJobStatusResponseBody Body;
        
        public GetJobStatusResponse() {
        }
        
        public GetJobStatusResponse(ValidatorExample.ValidationService.GetJobStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://validator.dmbasis.ru/phone/")]
    public partial class GetJobStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ValidatorExample.ValidationService.JobStatusResult GetJobStatusResult;
        
        public GetJobStatusResponseBody() {
        }
        
        public GetJobStatusResponseBody(ValidatorExample.ValidationService.JobStatusResult GetJobStatusResult) {
            this.GetJobStatusResult = GetJobStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetValidationResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetValidationResult", Namespace="http://validator.dmbasis.ru/phone/", Order=0)]
        public ValidatorExample.ValidationService.GetValidationResultRequestBody Body;
        
        public GetValidationResultRequest() {
        }
        
        public GetValidationResultRequest(ValidatorExample.ValidationService.GetValidationResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://validator.dmbasis.ru/phone/")]
    public partial class GetValidationResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid jobId;
        
        public GetValidationResultRequestBody() {
        }
        
        public GetValidationResultRequestBody(System.Guid jobId) {
            this.jobId = jobId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetValidationResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetValidationResultResponse", Namespace="http://validator.dmbasis.ru/phone/", Order=0)]
        public ValidatorExample.ValidationService.GetValidationResultResponseBody Body;
        
        public GetValidationResultResponse() {
        }
        
        public GetValidationResultResponse(ValidatorExample.ValidationService.GetValidationResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://validator.dmbasis.ru/phone/")]
    public partial class GetValidationResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ValidatorExample.ValidationService.ValidationResult[] GetValidationResultResult;
        
        public GetValidationResultResponseBody() {
        }
        
        public GetValidationResultResponseBody(ValidatorExample.ValidationService.ValidationResult[] GetValidationResultResult) {
            this.GetValidationResultResult = GetValidationResultResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : ValidatorExample.ValidationService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<ValidatorExample.ValidationService.ServiceSoap>, ValidatorExample.ValidationService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ValidatorExample.ValidationService.ValidateResponse ValidatorExample.ValidationService.ServiceSoap.Validate(ValidatorExample.ValidationService.ValidateRequest request) {
            return base.Channel.Validate(request);
        }
        
        public ValidatorExample.ValidationService.ValidationResult[] Validate(string phoneCode, string phoneNum) {
            ValidatorExample.ValidationService.ValidateRequest inValue = new ValidatorExample.ValidationService.ValidateRequest();
            inValue.Body = new ValidatorExample.ValidationService.ValidateRequestBody();
            inValue.Body.phoneCode = phoneCode;
            inValue.Body.phoneNum = phoneNum;
            ValidatorExample.ValidationService.ValidateResponse retVal = ((ValidatorExample.ValidationService.ServiceSoap)(this)).Validate(inValue);
            return retVal.Body.ValidateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ValidatorExample.ValidationService.ValidateBatchResponse ValidatorExample.ValidationService.ServiceSoap.ValidateBatch(ValidatorExample.ValidationService.ValidateBatchRequest request) {
            return base.Channel.ValidateBatch(request);
        }
        
        public System.Guid ValidateBatch(ValidatorExample.ValidationService.ValidationRequest[] batch, bool withManualChecking, string userName) {
            ValidatorExample.ValidationService.ValidateBatchRequest inValue = new ValidatorExample.ValidationService.ValidateBatchRequest();
            inValue.Body = new ValidatorExample.ValidationService.ValidateBatchRequestBody();
            inValue.Body.batch = batch;
            inValue.Body.withManualChecking = withManualChecking;
            inValue.Body.userName = userName;
            ValidatorExample.ValidationService.ValidateBatchResponse retVal = ((ValidatorExample.ValidationService.ServiceSoap)(this)).ValidateBatch(inValue);
            return retVal.Body.ValidateBatchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ValidatorExample.ValidationService.GetJobStatusResponse ValidatorExample.ValidationService.ServiceSoap.GetJobStatus(ValidatorExample.ValidationService.GetJobStatusRequest request) {
            return base.Channel.GetJobStatus(request);
        }
        
        public ValidatorExample.ValidationService.JobStatusResult GetJobStatus(System.Guid jobId) {
            ValidatorExample.ValidationService.GetJobStatusRequest inValue = new ValidatorExample.ValidationService.GetJobStatusRequest();
            inValue.Body = new ValidatorExample.ValidationService.GetJobStatusRequestBody();
            inValue.Body.jobId = jobId;
            ValidatorExample.ValidationService.GetJobStatusResponse retVal = ((ValidatorExample.ValidationService.ServiceSoap)(this)).GetJobStatus(inValue);
            return retVal.Body.GetJobStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ValidatorExample.ValidationService.GetValidationResultResponse ValidatorExample.ValidationService.ServiceSoap.GetValidationResult(ValidatorExample.ValidationService.GetValidationResultRequest request) {
            return base.Channel.GetValidationResult(request);
        }
        
        public ValidatorExample.ValidationService.ValidationResult[] GetValidationResult(System.Guid jobId) {
            ValidatorExample.ValidationService.GetValidationResultRequest inValue = new ValidatorExample.ValidationService.GetValidationResultRequest();
            inValue.Body = new ValidatorExample.ValidationService.GetValidationResultRequestBody();
            inValue.Body.jobId = jobId;
            ValidatorExample.ValidationService.GetValidationResultResponse retVal = ((ValidatorExample.ValidationService.ServiceSoap)(this)).GetValidationResult(inValue);
            return retVal.Body.GetValidationResultResult;
        }
        
        public int StartJob(System.Guid jobId) {
            return base.Channel.StartJob(jobId);
        }
    }
}
